version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: admin
    command: >
      bash -c "echo 'supersecretkey123456789' > /etc/mongo-keyfile &&
               chmod 400 /etc/mongo-keyfile &&
               chown mongodb:mongodb /etc/mongo-keyfile &&
               exec mongod --replSet rs0 --bind_ip_all --keyFile /etc/mongo-keyfile"
    healthcheck:
      test: >
        bash -c '
        mongosh --quiet -u root -p example --authenticationDatabase admin --eval "
        try {
          rs.status();
        } catch(e) {
          rs.initiate();
        }
        "'
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
